# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d2dabc3c2ef11809e9f1f4902d24bcdf1e8acb4d22f44ae8747aedb8bf5610beddd5165a95a45de8664994bccd5348544424549dfbeeaf128e45d87490ac5ff

test:
  secret_key_base: 261d891003b28731ffe819069f62343f764298a76e17de478dca7578dd57be8e48be012e50243b83d9c68048e87c6b1f042a71226798681ce36512a5898a59a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
